---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular-__CI_PROJECT_NAME__
  name: angular
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: angular
      port: 443
      targetPort: 443
      protocol: TCP
    - name: angular-2
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: angular-__CI_PROJECT_NAME__
---
