---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular-__CI_PROJECT_NAME__
  name: angular
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: angular-__CI_PROJECT_NAME__
---
