---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular-__CI_PROJECT_NAME__
    k8s-addon: ingress-nginx.addons.k8s.io
  name: angular
spec:
  clusterIP: None
  ports:
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: angular-__CI_PROJECT_NAME__
---
